language:
    - python

python:
  - "2.7"
  # Not yet supported
  # - "3.3"
  # - "3.4"

compiler:
    - gcc
    - clang

before_install:
    # Install conda
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
            wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        else
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda config --add channels conda-forge
    # Useful for debugging any issues with conda
    - conda info -a

install:
    # Create python environment with the dependencies
    - conda create -q -n env-pyboost_ipc python=$TRAVIS_PYTHON_VERSION numpy pytest boost cmake
    - source activate env-pyboost_ipc

script:
    - mkdir build
    - cd build
    - cmake .. -DCOMPILE_TESTS=True -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
    - cmake --build .
    - sudo make install
    - py.test ../source/python
