language:
    - python

python:
  - "2.7"
  - "3.3"
  - "3.4"

compiler:
    - gcc
    - clang

before_install:
    # Install cmake
    - mkdir /tmp/cmake-installation
    - cd /tmp/cmake-installation
    - touch more
    - chmod a+x more
    - wget http://www.cmake.org/files/v3.3/cmake-3.3.0-Linux-x86_64.sh --no-check-certificate
    - yes | sudo PATH=/tmp/cmake-installation:$PATH sh cmake-3.3.0-Linux-x86_64.sh --prefix=/opt
    - sudo ln -f -s /opt/cmake-3.3.0-Linux-x86_64/bin/cmake /usr/local/bin/cmake
    - cd -
    # Install conda
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
            wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        else
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    # Add boost ppa
    - sudo add-apt-repository -y ppa:boost-latest/ppa
    - sudo apt-get update

install:
    - sudo apt-get install libboost-python1.55-dev
    - # Create python environment with the dependencies
    - conda create -q -n env-pyboost_ipc python=$TRAVIS_PYTHON_VERSION numpy pytest
    - source activate env-pyboost_ipc

script:
    - mkdir build
    - cd build
    - cmake .. -DCOMPILE_TESTS=True
    - cmake --build .
    - sudo make install
    - py.test ../source/python
