language:
    - cpp
    - python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

compiler:
    - gcc
    - clang

install:
    - sudo apt-get install libboost-dev
    - sudo apt-get install cmake

script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
    - make install
    - py.test source/python
