language:
    - cpp
    - python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

compiler:
    - gcc
    - clang

before_install:
    - cd /tmp
    - wget http://www.cmake.org/files/v3.3/cmake-3.3.0-Linux-x86_64.sh
    - yes | sudo sh cmake-3.3.0-Linux-x86_64.sh --prefix=/opt
    - sudo ln -f -s /opt/cmake-3.3.0-Linux-x86_64/bin/cmake /usr/local/bin/cmake

install:
    - sudo apt-get install libboost-dev

script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
    - make install
    - ctest --output-on-failure
