package:
  name: pyboost_ipc
  version: 0.2

source:
  path: ../

requirements:
  build:
    - gcc [linux]
    - cmake >=3.0
    - python
    - libpython [win]
    - boost >=1.55
  run:
    - python
    - boost >=1.55

test:
  imports:
    - pyboost_ipc
